### ISSUE TITLE
Support for Rancher 2.0

### ISSUE THREAD

**Issue by loxy** [mxschmitt/ui-driver-hetzner#10]
Hi,

the current driver (1.0.1) isn't correctly working with Rancher 2.0. I cannot add a node template when creating a new cluster. Is there any support planned for Rancher 2.0?

Best regards,
Kersten

**Comment by mxschmitt** [comment]
@loxy 
There is already Rancher 2 support available on the `master` branch. Check it out here:
https://github.com/mxschmitt/ui-driver-hetzner/tree/master

**Comment by loxy** [comment]
Ah ok, nice. The 1.6 branch is the default and there was no hint for version 2.

**Comment by mxschmitt** [comment]
Oh okay, i will add it into the header of the readme. 👍

**Comment by loxy** [comment]
Great. Thank you!
