### ISSUE TITLE
Use existing SSH key from Hetzner

### ISSUE THREAD

**Issue by loxy** [mxschmitt/ui-driver-hetzner#11]
Hi,

currently it is not possible to use an existing ssh key in the Rancher UI through the docker-machine-driver-hetzner (`--hetzner-existing-key-path`, `--hetzner-existing-key-id`), right? (I'm talking about Rancher 2.0). So that every automatically created node gets the same ssh key...
Are there any workarounds, like some cloud init stuff? Or are there any plans to support that or is it not possible?

Best regards,
Kersten

**Comment by mxschmitt** [comment]
Hi @loxy 

I don't see any possibility, that we can create a server via Rancher 2 with a predefined SSH key.
So as you said, the best way in my mind would be to add your custom SSH key to your machines via Cloud-Init.

Best regards

Max

**Comment by mxschmitt** [comment]
I saw in the other official drivers, e.g. digital ocean and the directly created docker command no option to add an ssh key. Or did I miss something

**Comment by loxy** [comment]
Not that I'm aware of. Thank you!

**Comment by cecchisandrone** [comment]
I tried with cloud-init without success:
```
#cloud-config
ssh_authorized_keys:
  - ssh-rsa xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx root@host
```
An auto generated key overwrites this maybe. Did you have success in adding key with cloud-init?
