### ISSUE TITLE
Did not get it working with Rancher 2.6.x

### ISSUE THREAD

**Issue by exocode** [mxschmitt/ui-driver-hetzner#125]
Hi there, 

I tried ui-driver-hetzner with the latest Rancher 2.6.x version.

Error `undefined`

**Comment by crisrat** [comment]
I am getting a different error (of course, I removed the token from the form, but can't get to the second stage): 
![image](https://user-images.githubusercontent.com/5023897/140718827-50238d13-9e0c-4ff3-a04f-89e54a027bab.png)

Using RKE2, Rancher2.6.2

**Comment by mxschmitt** [comment]
So Rancher <=2.5 was working and 2.6 is not working anymore? I can setup a Rancher dev environment tomorrow and dig into it.

**Comment by olexiyb** [comment]
I was able to add using latest URL to 2.6

```
https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/3.5.0/docker-machine-driver-hetzner_3.5.0_linux_amd64.tar.gz
```

**Comment by exocode** [comment]
yes works, thank you!

**Comment by olexiyb** [comment]
I have latest Rancher v2.6.5 and try to install RKE2 and I can not bypass `new credential` screen
![image](https://user-images.githubusercontent.com/352780/175048492-59f2f533-d821-41ce-8e80-1571f88b9dcc.png)
Add new token
![image](https://user-images.githubusercontent.com/352780/175048789-deeecffe-c48d-4f60-b198-949224b1b48b.png)
And there is no token to select
![image](https://user-images.githubusercontent.com/352780/175048905-2084cf3a-16c5-44ab-a814-c0edeb59f1bc.png)

**Comment by hoerup** [comment]
yes, it seems like this project doesnt work with the rke2/k3s setup flow 
But rke1 seems fine

**Comment by rr4444** [comment]
The problem seems to be back

**Comment by cristianrat** [comment]
> The problem seems to be back

I never got it working correctly with rke so I switched the k8s flavour :)
