### ISSUE TITLE
Placements group support

### ISSUE THREAD

**Issue by anebi** [mxschmitt/ui-driver-hetzner#126]
Hello,

Hetzner has relelased a new functionality called "PLACEMENT GROUPS" and I believe that this functionality is very important for Cluster HA setups and stability. 

The support was already added to : https://github.com/JonasProgrammer/docker-machine-driver-hetzner

Thanks and regards,
Ali Nebi

**Comment by mxschmitt** [comment]
This got implemented by @4ch3los in #127, thank you so much!
