### ISSUE TITLE
Node Template UI not working

### ISSUE THREAD

**Issue by pehbehbeh** [mxschmitt/ui-driver-hetzner#13]
I installed the driver in Rancher 2.0 and all I get is a blank UI (and the page freezes) when trying to create a new node template. I also get the following error: 

```
opcode-compiler.js:36 Uncaught TypeError: (0 , this.funcs[r]) is not a function
    at e.compile (opcode-compiler.js:36)
    at n.i.expr (opcode-compiler.js:1157)
    at n.i.compileParams (opcode-compiler.js:1509)
    at n.i.compileArgs (opcode-compiler.js:1520)
    at n.i.modifier (opcode-compiler.js:1283)
    at opcode-compiler.js:70
    at e.compile (opcode-compiler.js:36)
    at e.compile (opcode-compiler.js:763)
    at Object.evaluate (runtime.js:493)
    at e.evaluate (runtime.js:30)
...
```

### Screenshot

<img width="897" alt="bildschirmfoto 2018-05-12 um 16 32 48" src="https://user-images.githubusercontent.com/133831/39958372-47d80818-5602-11e8-8e00-4af53fed3997.png">

**Comment by pehbehbeh** [comment]
Thanks for the quick reply! I followed the instructions from the `master` branch. So I am using:

* Download URL: `https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/1.1.0/docker-machine-driver-hetzner_1.1.0_linux_amd64.tar.gz`
* Custom UI URL: `https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js`
* Whitelist Domains: `storage.googleapis.com`

Seems correct to me... 😞 Anything else I can try?

**Comment by mxschmitt** [comment]
Hm, I've tested it and it works with the latest Rancher 2 version a few minutes ago. Could you:
- try to open the DevTools and clear the cache (maybe broken Rancher UI version)
- Search in the DevTools in the network tab for "hetzner", and check if the latest http request of the `component.js` returns "a buch of code" 😄 

I saw, that you are using Google Chrome => That's good. One of the latest versions?

**Comment by pehbehbeh** [comment]
I am using Rancher UI Version `v2.0.42`. Clearing the  cache does not help.

When loading the "Add Node Template" UI the `component.js` request does return "a bunch of code":

```
/* v----- Do not change anything between here
 *       (the DRIVERNAME placeholder will be automatically replaced during build) */
define('ui/components/node-driver/driver-hetzner/component', ['exports', 'ember', 'shared/components/node-driver/driver-hetzner/component'], function (exports, _ember, _component) {
  exports['default'] = _component['default'];
});

...
```

Google Chrome is also up to date: `Version 66.0.3359.170`.

**Comment by mxschmitt** [comment]
@pehbehbeh fixed in the latest version

**Comment by pehbehbeh** [comment]
Looks good - thanks a lot!
