### ISSUE TITLE
Github code apparently not aligned with the published component.js

### ISSUE THREAD

**Issue by eedugon** [mxschmitt/ui-driver-hetzner#130]
If I'm not mistaken, the `component.js` mentioned in the main `README` and available at https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js is not aligned with the code of the `main` branch or with any other branch as far as I could tell.

Would it be possible to share the code used to build the current `component.js` that supports Rancher 2.x or let me know how exactly to build a driver that generates the same component.js that is already published? Otherwise I won't be able to do any change or propose any PR.

I'm unable to build the driver from the source and make it working with Rancher 2.6 with the `main` branch but instead I can do reverse engineering and do changes in the published `component.js` without problems (I have implemented a change to support the creation of servers `only` in private networks (together with the `machine driver 3.8.0` and it works fine).

Taking a look at the published code at `storage.googleapis.com` (component.js) is clearly not aligned with the github repo and the outcome of the manual build, although I could be missing something silly (i'm not a developer).

If anyone can help me with that it would be really appreciated, as it would allow me to share some improvements via PRs.

**Comment by olastor** [comment]
@eedugon The `component.js` at https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js seems to be the bundled version of what's in the git repo.

I just checked it, you can verify it like this:

```
git clone https://github.com/mxschmitt/ui-driver-hetzner
cd ui-driver-hetzner
wget https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js
npm install
npm run build
diff component.js dist/component.js
# => no difference
```

`dist/component.js` is the one compiled locally.

**Comment by eedugon** [comment]
@olastor , thanks a lot, I will review this soon.
I was using the dockerfile provided in the repo, but I will analyze this further, thanks!
