### ISSUE TITLE
Custom UI URL for Hetzner CSI is no available

### ISSUE THREAD

**Issue by FrolovVyacheslav** [mxschmitt/ui-driver-hetzner#134]
Greetings. Faced the problem of lack of access to the UI. As a result, it is impossible to create and edit Node templates.
In Rancher :
```There was an error trying to load custom driver hetzner. Please verify the custom node driver settings.```

In browser https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js:
```
UserProjectAccountProblem
The project to be billed is associated with a closed billing account.
The billing account for the owning project is disabled in state closed
```
I would be very grateful if someone could tell me how to restore access to the user interface in Rancher for Hetzner CSI

**Comment by zgaduj** [comment]
You can simply replace the url with this from github as a raw file  https://raw.githubusercontent.com/mxschmitt/ui-driver-hetzner/master/component/component.js  
  
It work's for me :)

**Comment by zgaduj** [comment]
Here you go: https://storage.googleapis.com/ui-hetzner/v0.0.1/component.js

**Comment by FrolovVyacheslav** [comment]
Thanks, it works!

**Comment by FrolovVyacheslav** [comment]
Solved
