### ISSUE TITLE
Add nodes not managed by this plugin to the cluster

### ISSUE THREAD

**Issue by tfohlmeister** [mxschmitt/ui-driver-hetzner#15]
Is there a simple way to add a node using SSH / docker rancher-agent similar to the generic provider?
My Rancher VM is pretty beefy and I would like to use it as a worker node.
Thanks!

**Comment by mxschmitt** [comment]
Hi @tfohlmeister,
not sure what you mean. Could you provide me some more information so I can dig more into this specific issue?
The best would be, that another driver has already integrated this, so I can see directly how it works there.

Best regards

Max

**Comment by jhsware** [comment]
He probably wants you to expose the rancher-agent command with options. Not sure if this is within the scope of this package. I would close this as "won't fix" if I were you.
