### ISSUE TITLE
not working in rancher 2.1.0

### ISSUE THREAD

**Issue by andreastoermer** [mxschmitt/ui-driver-hetzner#17]
Hi,

today, I upgrade my rancher version to 2.1.0.

Now i've got the following error message, when i want to add new templates:

`0:29715 Uncaught TypeError: Cannot read property 'manager' of null
    at Object.evaluate (0:29715)
    at e.evaluate (0:28614)
    at e.evaluateSyscall (0:31506)
    at e.evaluateInner (0:31478)
    at e.evaluateOuter (0:31470)
    at e.next (0:33421)
    at e.execute (0:33406)
    at i.handleException (0:32362)
    at e.handleException (0:32535)
    at e.throw (0:32269)
(anonymous) @ 0:29715
e.evaluate @ 0:28614
e.evaluateSyscall @ 0:31506
e.evaluateInner @ 0:31478
e.evaluateOuter @ 0:31470
e.next @ 0:33421
e.execute @ 0:33406
i.handleException @ 0:32362
e.handleException @ 0:32535
e.throw @ 0:32269
n.evaluate @ 0:29300
e.execute @ 0:32256
e.rerender @ 0:32561
l.render @ 0:41200
A @ 0:45847
e._renderRoots @ 0:41481
e._renderRootsTransaction @ 0:41514
e._revalidate @ 0:41557
e.invoke @ 0:34688
e.flush @ 0:34604
e.flush @ 0:34766
e._end @ 0:35237
_boundAutorunEnd @ 0:34934
characterData (async)
s @ 0:34444
e._scheduleAutorun @ 0:35423
e._end @ 0:35242
_boundAutorunEnd @ 0:34934
characterData (async)
s @ 0:34444
e._scheduleAutorun @ 0:35423
e._end @ 0:35242
_boundAutorunEnd @ 0:34934
characterData (async)
s @ 0:34444
e._scheduleAutorun @ 0:35423
e._end @ 0:35242
_boundAutorunEnd @ 0:34934
characterData (async)
s @ 0:34444
e._scheduleAutorun @ 0:35423
e._end @ 0:35242
_boundAutorunEnd @ 0:34934
characterData (async)
s @ 0:34444
e._scheduleAutorun @ 0:35423
e._end @ 0:35242
_boundAutorunEnd @ 0:34934
characterData (async)
s @ 0:34444
e._scheduleAutorun @ 0:35423
e._end @ 0:35242
_boundAutorunEnd @ 0:34934
characterData (async)
s @ 0:34444
e._scheduleAutorun @ 0:35423
e._end @ 0:35242
_boundAutorunEnd @ 0:34934
characterData (async)
s @ 0:34444
e._scheduleAutorun @ 0:35423
e._ensureInstance @ 0:35415
e.schedule @ 0:35050
(anonymous) @ 0:54960
x @ 0:64352
E @ 0:64317
w @ 0:64325
(anonymous) @ 0:64448
o.onload @ 0:257418
load (async)
(anonymous) @ 0:257416
(anonymous) @ 0:64443
e @ 0:64900
e.loadScript @ 0:257406
(anonymous) @ 0:231313
loadCustomUi @ 0:231302
(anonymous) @ 0:231210
v @ 0:64239
T @ 0:64417
C @ 0:64402
e.invoke @ 0:34690
e.flush @ 0:34604
e.flush @ 0:34766
e._end @ 0:35237
e.end @ 0:34964
e._run @ 0:35282
e._join @ 0:35258
e.join @ 0:35019
d @ 0:23941
e.handler @ 0:42891
(anonymous) @ 0:60090
dispatch @ 0:13099
g.handle @ 0:12907`

**Comment by jannylund** [comment]
I just upgraded my test-cluster and noticed the same thing. All UI is dead, meaning it's not possible to edit, clone or add new node-templates.

**Comment by mxschmitt** [comment]
Hi @jannylund @andreastoermer,

it's now fixed. It was due a big change introduced in Rancher 2.1 in the custom ui driver handling.

Please let me know, if all is now working as expected.

Best regards

Max

**Comment by andreastoermer** [comment]
@mxschmitt How can i update the component.js? I delete the old node driver, than add it again, with the informations i found here (https://github.com/mxschmitt/ui-driver-hetzner) and try it again in my  old cluster (but it did not work). did i something wrong?

**Comment by jannylund** [comment]
@mxschmitt Thanks, I can confirm it works.

**Comment by kiloreux** [comment]
I am having this issue on a newly installed cluster Rancher v2.1.4 with latest version from this repo. Any idea or solution for it ?
