### ISSUE TITLE
Can't create node from snapshot

### ISSUE THREAD

**Issue by Negashev** [mxschmitt/ui-driver-hetzner#19]
Maybe lost value?

after create cluster say that `missing image`

rancher 2.1.1
driver 1.2.2

![annotation 2018-11-27 094328](https://user-images.githubusercontent.com/4653589/49063769-75e01200-f229-11e8-90e1-fa790c8a66fa.jpg)

**Comment by mxschmitt** [comment]
Hi @Negashev,

it's not implemented yet to use an image, sorry. I will add this once I have time, maybe this weekend.

Best regards

Max

**Comment by Negashev** [comment]
Hi @mxschmitt,

I looked at your ui-driver, I will try to make a pull request.

**Comment by mxschmitt** [comment]
If you have any questions, feel free to ask :)

For development I used ngrok.com to expose the `grunt server` to the internet. This public URL I set then inside Rancher in the driver settings.

**Comment by Negashev** [comment]
@mxschmitt Thank!

The only problem now is the embet, I don’t know it) it’s easy, but I can’t get it to be pulled into a custom action target with imageId and imageName, right now I thought to use only imageId in api

```html
        <select class="form-control" onchange={{action 'selectImage'}}>
          {{#each imageChoices as |choice|}}
            <option value={{choice.id}}>{{choice.description}}</option>
          {{/each}}
        </select>
```

```js

  actions: {
    selectImage(val){
        console.log(val); // I'm js debug expert :)
    },
  }
```

The Best solution - filter `model.hetznerConfig` and send only Image Name (for official) key or Image ID (for snapshot)

My Simple solution tray to send only Image ID, because ID is unique in returned json from hetzner api:

![annotation 2018-11-27 144543](https://user-images.githubusercontent.com/4653589/49079993-3dedc480-f253-11e8-8334-3a24ef20ff04.jpg)

**Comment by Negashev** [comment]
Interested create `Node Template`, and from my brouser rancher UI send:
![annotation 2018-11-27 151059](https://user-images.githubusercontent.com/4653589/49081116-ca4db680-f256-11e8-882a-703447eae83d.jpg)

But rancher Server return:
![annotation 2018-11-27 150953](https://user-images.githubusercontent.com/4653589/49081129-d6d20f00-f256-11e8-9e37-0bf6c78713fb.jpg)


`image` key appand with ubuntu16? wtf? (in some situations i got image with my tag discription (bug on rancher server (or hetzner driver)))

**Comment by Negashev** [comment]
Oh... okay it's work with snapshots) but i got problem with IDs (some randoms selected maybe i need to fix imageId to str)
```html
      <div class="col-md-4">
        <select class="form-control" onchange={{action (mut model.hetznerConfig.imageId) value="target.value" }}>
          {{#each imageChoices as |choice|}}
            <option value={{choice.id}} selected={{eq model.hetznerConfig.imageId choice.id}}>{{choice.description}}</option>
          {{/each}}
        </select>
      </div>
```

```js
// bootstrap
    let config = get(this, 'globalStore').createRecord({
      type: '%%DRIVERNAME%%Config',
      serverType: 'cx21', // 4 GB Ram
      serverLocation: 'nbg1', // Nuremberg
      imageId: 1, // 'ubuntu-16.04' - go to string? 
      userData: ''
    });

// validate
    // use only IDs
    if ( get(this, 'model.%%DRIVERNAME%%Config.image') ) {
      delete this.get('model.%%DRIVERNAME%%Config').image;
    }
```

**Comment by gadelkareem** [comment]
Any updated on this?

**Comment by mxschmitt** [comment]
Hi  @gadelkareem,

are your changes in GitHub? So I can test it locally.

Best regards

Max

**Comment by gadelkareem** [comment]
No, I was just checking if you found any fix yet :)

**Comment by Negashev** [comment]
@mxschmitt 
I failed, lack of knowledge in the embet (

**Comment by mxschmitt** [comment]
Oh, I thought you are the same person who requested and implemented the change....
My fault 😄 

@Negashev So now you got a solution for your specific issue?

**Comment by Negashev** [comment]
@mxschmitt 
Yes, i find that we can use only hetzner-image-id (and ignore hetzner-image-name), but i can't fix it on UI, I can not deal with embet.

**Comment by mxschmitt** [comment]
Would be great if you could check in your changes into GitHub so I can reproduce it on my test environment and maybe fix it 👍

**Comment by gadelkareem** [comment]
Sure, I am looking into it.

**Comment by Negashev** [comment]
@mxschmitt

All changes here

https://github.com/mxschmitt/ui-driver-hetzner/issues/19#issuecomment-442042301

**Comment by mxschmitt** [comment]
@Negashev 
I tried to reproduce your changes but it is working fine: 👍

Testcases:
- Deploy Cluster with Debian 9
- Deploy Cluster with Custom Image

The custom image Hetzner Cloud deployment works fine but the docker-machine-driver could not be registered because of the SSH Key stuff afaik. So there is an endless delete/create loop.

The deployment of debian 9 also works as expected, successful docker-machine-driver registration.

**Comment by vitobotta** [comment]
Just noticed this from googling after creating another issue... Sorry. Do I gather that it is now possible to select a snapshot for the node template?

**Comment by mxschmitt** [comment]
> Just noticed this from googling after creating another issue... Sorry. Do I gather that it is now possible to select a snapshot for the node template?

yes, it should be possible

**Comment by vitobotta** [comment]
Yeah I tried using a snapshot and it worked, although I was trying with RancherOS and Rancher could only create the servers from the snapshot but not proceed with the provisioning...
