### ISSUE TITLE
Driver not working in Rancher 2.2.0-rc2

### ISSUE THREAD

**Issue by vistalba** [mxschmitt/ui-driver-hetzner#26]
I tried to use the driver in Rancher 2.2.0-rc2 to test the implementation of weave network plugin.
Unfortunately the driver isn't working anymore in this version. 

After adding to rancher it stucks on state "downloading".

I know, this is a pre-release of rancher. But maybe there is a easy and short fix for that?

**Comment by mxschmitt** [comment]
Thanks for reporting!
I will investigate into this issue.
Best regards
Max

**Comment by mxschmitt** [comment]
![screen shot 2019-02-25 at 08 58 43](https://user-images.githubusercontent.com/17984549/53322427-afcdbc80-38db-11e9-985f-f2ca29fb16ff.png)

Hi again,

in the `Drivers` tab, you have to select `Node Drivers`. When you will choose this one, the driver will be created as expected.

Best regards

Max
