### ISSUE TITLE
Make provisioning block storage volumes possible

### ISSUE THREAD

**Issue by Troyhy** [mxschmitt/ui-driver-hetzner#28]
Hezner cloud supports now block storage volumes that can be attached to host. -> https://www.hetzner.com/cloud These volumes are now supported in all locations ( Helsinki, Nuremberg and Falkenstein )
It would be create feature that you could define also volume provisioned with the machine.

**Comment by mxschmitt** [comment]
Upstream tracked issue: https://github.com/JonasProgrammer/docker-machine-driver-hetzner/issues/17

**Comment by mxschmitt** [comment]
Closed, take a look in the upstream issue for more reference and how you can use it. :)
