### ISSUE TITLE
Rancher 2.2.1 compatibility issues

### ISSUE THREAD

**Issue by gabrielke** [mxschmitt/ui-driver-hetzner#30]
- logo not displayed
- cannot add node template

seemingly there is no place to enter the API key

**Comment by gabrielke** [comment]
Tried the same with 2.2.0, works perfectly.

**Comment by mxschmitt** [comment]
Should be fixed (docs) in #29. Have you selected `Node Driver` instead of `Cluster Driver`?

**Comment by gabrielke** [comment]
Yes of course selected "node driver"

**Comment by mxschmitt** [comment]
Hi,
I tried to reproduce your issue, but I can't. I've used also Rancher 2.1.1 with the latest tag from the Docker Hub and everything is working fine.

To reproduce:

1. Install Rancher test environment via
```
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -v /opt/rancher:/var/lib/rancher \
  rancher/rancher:latest
```

2. Add Node Driver via the URLs in the README

3. Create Cluster and Nodes using my Node Driver.

I guess, that you have forgotten to whitelist the `storage.googleapis.com` domain. So the assets e.g. the logo can't be fetched.

**Comment by mxschmitt** [comment]
I will close this issue now because there were no response after 5 days. If there are any more issues referring to this issue, feel free to ping me and I will reopen it. :)

**Comment by mschickervxob** [comment]
I have exactly the same issue with fresh install of Rancher/Stable 2.2.2.

Add Note Template shows nothing apart the logo.

https://monosnap.com/file/Pa0rUzW7G18NFNv9oslyoLkQdbjHc6

<img width="1266" alt="Rancher_2019-05-02_14-45-38" src="https://user-images.githubusercontent.com/10919430/57076206-5c1b8d00-6ce9-11e9-95a2-b3f014fcb1e1.png">

**Comment by mschickervxob** [comment]
Just tried a different browser (Safari instead of Brave) - here it works.

**Comment by mxschmitt** [comment]
Interesting, because it's also is built on top on Chromium. Maybe it blocks some important HTTP requests. Would be awesome if you can investigate maybe via checking the DevTools => Network tab.
Thanks!
