### ISSUE TITLE
ssh into server

### ISSUE THREAD

**Issue by Askotion** [mxschmitt/ui-driver-hetzner#32]
Hey there,

I was wondering if it's possible to ssh into one of the machines in order to install e.g helm etc.
Or is there another solution to install such things?

Thanks for your work! :)

**Comment by mxschmitt** [comment]
Hi @Askotion,

you can, but you have to use the SSH keys, which were generated during the provisioning. For more information check out the Rancher CLI (ssh parameter): https://rancher.com/docs/rancher/v2.x/en/cli/

Alternatively you can also download the SSH keys via the webinterface of Rancher iteself under Hosts.

But it's not very convenient as far as I know.
