### ISSUE TITLE
Weird...can't SSH into the nodes provisioned with Rancher 2.2.2

### ISSUE THREAD

**Issue by vitobotta** [mxschmitt/ui-driver-hetzner#33]
Hi! Is this driver compatible with Rancher 2.2.2? I have upgraded and it seems like I can't SSH into the nodes provisioned in Hetzner Cloud with Rancher. I opened an issue in Racher as well (https://github.com/rancher/rancher/issues/19720) but I was wondering if it could be a compatibility issue or something like that? Thanks!

**Comment by mxschmitt** [comment]
Hi, I've just tested it with Rancher 2.2.2 and it works fine, so I can't reproduce it. In the morning someone reported the same issue: #32. But no clue, why this should not work.

**Comment by vitobotta** [comment]
Thanks for looking into it! Weird, I have tried several times and each time I couldn't SSH into the nodes if created from Rancher. If I create the nodes with Ansible first and then I set up Kubernetes with Rancher as "custom" nodes it doesn't affect my SSH present on the nodes and I can still SSH into them. No idea of what has changed. :(

**Comment by mxschmitt** [comment]
Closed, due that's definitely no `ui-driver-hetzner` issue and I can't reproduce it.
