### ISSUE TITLE
Server does not provisioning

### ISSUE THREAD

**Issue by shyim** [mxschmitt/ui-driver-hetzner#35]
I have created one CX11 with Debian 9. It's in infinite loop of provisioning. After a hour it was still in provisioning. 

I have done the same using Ubuntu 16.04 and it was active for a minute and then its now offline
![image](https://user-images.githubusercontent.com/6224096/56867193-df379d00-69e2-11e9-84ac-164682e579f1.png)

It looks like it got deleted. I can't find it anymore in my account

This tool hates me

**Comment by mxschmitt** [comment]
Please try to recreate the Node. Which version of Rancher are you using?

**Comment by shyim** [comment]
Same
Rancher: v2.2.2

Here my config
![image](https://user-images.githubusercontent.com/6224096/56908754-399a3180-6aa7-11e9-94f1-4f6515a41a54.png)
![image](https://user-images.githubusercontent.com/6224096/56908770-41f26c80-6aa7-11e9-967e-80b9a16bbde5.png)
![image](https://user-images.githubusercontent.com/6224096/56908785-49b21100-6aa7-11e9-8956-4d88cdc333e4.png)

Its doing 5 minutes something and deleting the vm in a infinite loop

**Comment by mxschmitt** [comment]
Not sure what the issue in your case is. Are you maybe using some kind of private networking?
This `ui-driver` has now about 500+ users and nobody has such an issue. You can try to manually connect to a Node via SSH and check logs or run the Docker installation script manually. Maybe you see then what the issue is.

**Comment by n-moser** [comment]
I have exactly the same problem with Rancher 2.2.3, CX41 and Debian 9. @shyim did you solve the problem?

**Comment by mxschmitt** [comment]
> I have exactly the same problem with Rancher 2.2.3, CX41 and Debian 9. @shyim did you solve the problem?

which location? I will try later to reproduce it.

**Comment by n-moser** [comment]
I solved it, I had a typo in the StorageDriver.
