### ISSUE TITLE
Add Rancher 2 Support

### ISSUE THREAD

**Issue by mxschmitt** [mxschmitt/ui-driver-hetzner#4]
The skeleton-driver template was updated: https://github.com/rancher/ui-driver-skel/pull/7

// Edit: 16.03.18 - Waiting for a fix of https://github.com/rancher/rancher/issues/12113 in order to continue work.
// Edit: 27.03.18 - I've made the changes, and it's working. But we are depending on this PR for now: https://github.com/rancher/rancher/pull/12309

**Comment by errorsandwarnings** [comment]
I tried your plugin. Its awesome !! 👍 
You should definitely do a rancher 2 support.

**Comment by mxschmitt** [comment]
@errorsandwarnings @pnull @san4io
If you want to try it out, add a new rancher 2 driver with the following properties:

| Download URL | Custom UI URL | Whitelist Domain |
| ---------------- | ----------------- | ------------------- |
| https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/1.1.0/docker-machine-driver-hetzner_1.1.0_linux_amd64.tar.gz | http://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js | storage.googleapis.com |

The issue with https:// ui driver URLs does still exists, but we can simply use http:// as a workaround until the PR has been accepted for now.

Best regards

Max

**Comment by mxschmitt** [comment]
I'm closing this issue for now because the PR has been merged, so it can be regularly used in normal rancher builds. :)
