### ISSUE TITLE
Bug: „Flag provided but not defined: -hetzner-networks; Timeout waiting for ssh key„

### ISSUE THREAD

**Issue by vistalba** [mxschmitt/ui-driver-hetzner#41]
I added a network to my node template and created a new node. This ends with error:
`Flag provided but not defined: -hetzner-networks; Timeout waiting for ssh key`

The network is already created in hetzner console and is also visible in node template.

Rancher v2.2.5

**Comment by mxschmitt** [comment]
> I added a network to my node template and created a new node. This ends with error:
> `Flag provided but not defined: -hetzner-networks; Timeout waiting for ssh key`
> 
> The network is already created in hetzner console and is also visible in node template.
> 
> Rancher v2.2.5

Hi vistalba,

I will try to reproduce it and will let you know in a couple of minutes.

**Comment by mxschmitt** [comment]
@vistalba which Operating System, Docker Version and Storage driver have you used while configuring your Node Template?

**Comment by vistalba** [comment]
@mxschmitt

Ubuntu 18.04
Datacenter: nbg
Sizeing: cx21
Docker: recommended (https://releases.rancher.com/install-docker/18.09.sh )

I‘ve also a cloud-init script, but that shouldn‘t be a problem.

**Comment by mxschmitt** [comment]
@vistalba Unfortunately I can't reproduce this issue on my side. Tried ubuntu 18.04 with exact this docker version. With and without internal networks and it works without any issues.

**Comment by vistalba** [comment]
@mxschmitt 
Did you use rancher:v2.2.5 that was released today?

Do I‘ve to do some additional steps in the Hetzner Console exept just create a network with a name and a ipv4 CIDR?

**Comment by mxschmitt** [comment]
@vistalba you just have to create a network and have to specify the Rancher internal IP of your private network as server-url:
![image](https://user-images.githubusercontent.com/17984549/61290110-5d7a3300-a7cb-11e9-89eb-ae569374368c.png)
Important is, that also your Rancher instance is in this private network.

**Comment by vistalba** [comment]
Does this mean the node created by your driver only have a private interface? No additional one with a public ip?

**Comment by mxschmitt** [comment]
> Does this mean the node created by your driver only have a private interface? No additional one with a public ip?

Nope, but it does not make much sense when you use the public network when there is a private one available. In general it should also work by using the public external IP, but not intended. A private network is simply another network interface which is available.

**Comment by vistalba** [comment]
Yes, i know. As I read in hetzner documentation there will be just an additional interface with a private ip on the server. So I will use the internal one for all traffic inside the cluster and the public ones for all ingress traffic. The rancher server isn‘t in the private subnet but reachabe public.
