### ISSUE TITLE
hetznerConfig networks=NotNullable

### ISSUE THREAD

**Issue by BamButz** [mxschmitt/ui-driver-hetzner#48]
Hi,

I have noticed that since the network feature was implemented I can not edit my templates without a network being selected. This problem does not exist when I create a new template.

**Error message**
Validation failed in API: hetznerConfig networks=NotNullable 422:

**Comment by mxschmitt** [comment]
@BamButz so to sum up, old templates can't be adjusted with new Networks right?

**Comment by BamButz** [comment]
Nope, no template can be edited if there are no networks.

Reproducing:
- Get api key from a fresh project without private networks
- Create a new template using that api key
- Edit template (change title or anything)
