### ISSUE TITLE
Can't close the "Edit node template" dialog

### ISSUE THREAD

**Issue by FedeBev** [mxschmitt/ui-driver-hetzner#67]
I'm not able to close the __Edit node template__ dialog: when I click on the `cancel` button nothing happen and I can see the following error in console: `Uncaught TypeError: this.cancel is not a function`.

Rancher version: 2.3.1

**EDIT:**
Potentially related to [rancher issue 21618](https://github.com/rancher/rancher/issues/21618)

Thanks

**Comment by mxschmitt** [comment]
Seems to be not relevant anymore right?
