### ISSUE TITLE
Add support Cloud-init

### ISSUE THREAD

**Issue by blar** [mxschmitt/ui-driver-hetzner#7]
If a new server is created at console.hetzner.cloud its possible to add a cloud-init to configure the new server. Can you add this to the UI in Rancher?

**Comment by mxschmitt** [comment]
Hi,
yep I could do that, but first we need to add it to the hetzner-docker-driver. I have already created there an upstream issue: https://github.com/JonasProgrammer/docker-machine-driver-hetzner/issues/10 so that you can track it there.
Best regards
Max

**Comment by mxschmitt** [comment]
Hi Folks,
I've integrated it. To use it, just use the latest version from the community-catalog.
Best regards
Max
