### ISSUE TITLE
rancher 2.3.3 expects driver file name kontainer-engine-driver-*

### ISSUE THREAD

**Issue by robbatt** [mxschmitt/ui-driver-hetzner#74]
tried to install this driver in a new rancher 2.3.3 instance on a debian 10 machine with docker 19.03 and got following error in the rancher/rancher container log:

`2019/12/05 11:58:46 [INFO] update kontainerdriver kd-x4h2c
2019/12/05 11:58:46 [ERROR] Returning previous error: failed to find driver in archive. There must be a file of form kontainer-engine-driver-*
2019/12/05 11:58:46 [ERROR] KontainerDriverController kd-x4h2c [mgmt-kontainer-driver-lifecycle] failed with : failed to find driver in archive. There must be a file of form kontainer-engine-driver-*
`
the actual driver binary in the archive is named "docker-machine-driver-hetzner"
the cluster drivers state in the ui is getting stuck on "downloading"

**Comment by mxschmitt** [comment]
Be sure to select Node driver and not Cluster driver (first idea).

**Comment by robbatt** [comment]
that did it, thanks
