### ISSUE TITLE
kubelet fails to start when using external cloud provider

### ISSUE THREAD

**Issue by kozy** [mxschmitt/ui-driver-hetzner#77]
Hi and thanks for the great tool. It seems to work pretty flawless, apart from the following:
 
I'm trying to bring up a cluster and it works, unless i set 

`--cloud-provider=external `

I need that because of [hcloud-cloud-controller-manager](https://github.com/hetznercloud/hcloud-cloud-controller-manager).  

It seems to setup fine for a couple of minutes but the status of the nodes remains 'waiting to register with Kubernetes' and after a while I get an error above saying

`[workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [<ip2>]: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused, log: caused by: Not Found]
`
The ranger log contains the following. I substituted some ips with ip1,2

`
-- snip --
2019/12/14 20:19:03 [INFO] Restarting container [kubelet] on host [<ip1>], try #1
2019/12/14 20:19:03 [INFO] cluster [c-ml72h] provisioning: [sidekick] Sidekick container already created on host [<ip2>]
2019/12/14 20:19:03 [INFO] Restarting container [kubelet] on host [<ip2>], try #1
2019/12/14 20:19:03 [INFO] cluster [c-ml72h] provisioning: [healthcheck] Start Healthcheck on service [kubelet] on host [<ip2>]
2019/12/14 20:19:03 [INFO] cluster [c-ml72h] provisioning: [healthcheck] Start Healthcheck on service [kubelet] on host [78.47.185.86]
2019/12/14 20:19:03 [INFO] cluster [c-ml72h] provisioning: [healthcheck] Start Healthcheck on service [kubelet] on host [<ip1>]
2019/12/14 20:19:53 [ERROR] cluster [c-ml72h] provisioning: [workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [<ip2>]: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused, log: caused by: Not Found]
2019/12/14 20:19:53 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/12/14 20:19:53 [ERROR] ClusterController c-ml72h [cluster-provisioner-controller] failed with : [workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [<ip2>]: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused, log: caused by: Not Found]`

When I log into a node with an error it seems kubelet is restarting and contains the following error

`-- snip --
 I1214 20:28:15.675659    3509 flags.go:33] FLAG: --volume-stats-agg-period="1m0s"
I1214 20:28:15.675722    3509 feature_gate.go:216] feature gates: &{map[]}
I1214 20:28:15.675814    3509 feature_gate.go:216] feature gates: &{map[]}
I1214 20:28:15.676257    3509 mount_linux.go:153] Detected OS without systemd
I1214 20:28:15.677822    3509 server.go:410] Version: v1.16.3
I1214 20:28:15.678046    3509 feature_gate.go:216] feature gates: &{map[]}
I1214 20:28:15.678251    3509 feature_gate.go:216] feature gates: &{map[]}
W1214 20:28:15.678577    3509 plugins.go:115] WARNING: aws built-in cloud provider is now deprecated. The AWS provider is deprecated and will be removed in a future release
I1214 20:28:15.678946    3509 aws.go:1212] Building AWS cloudprovider
I1214 20:28:15.679164    3509 aws.go:1178] Zone not specified in configuration file; querying AWS metadata service
F1214 20:28:15.680747    3509 server.go:271] failed to run Kubelet: could not init cloud provider "aws": unable to determine AWS zone from cloud provider config or EC2 instance metadata: EC2MetadataError: failed to make EC2Metadata request
caused by: Not Found
`

Any ideas where this goes wrong? Does the ui driver depend on a certain configuration?

Thanks!

**Comment by kozy** [comment]
Okay I found it. Iit seems the kubelet gets `--cloud-provider=aws`

After digging into it it seems that rancher expects you to update the config for the cloud provider and it helps you out by setting some defaults for aws

**Comment by spatialy** [comment]
Hi @kozy, you where able to set --cloud-provider=external withou rancher missing around with AWS?
We as well need to use hcloud-cloud-controller.

Any guide?

Best
