### ISSUE TITLE
RancherOS 

### ISSUE THREAD

**Issue by vitobotta** [mxschmitt/ui-driver-hetzner#78]
Hi! I'm currently using Ubuntu as the OS for my nodes but I was thinking of using RancherOS instead. Can I use the node driver with this OS? If yes how? Should I create a server manually, install RancherOS and create a snapshot? Can I select a snapshot as the image in a node template? Thanks!

**Comment by mxschmitt** [comment]
It's not intended to use RancherOS. Or I have not investigated into make it work with RancherOS or CoreOS.

**Comment by vitobotta** [comment]
Thanks. I gave up on the idea, it seems to complicated for other reasons as well :)
