### ISSUE TITLE
Driver installation remains stuck in Downloading state

### ISSUE THREAD

**Issue by PriyankPa** [mxschmitt/ui-driver-hetzner#80]
The installation remains stuck in **Downloading** state. I waited overnight but it is still the same:

![image](https://user-images.githubusercontent.com/3187668/73906314-7f064d80-48c8-11ea-9303-d6b2fe1f82fb.png)

I had used this driver successfully in previous installation of Rancher.

Worked in this version:
![image](https://user-images.githubusercontent.com/3187668/73906373-b37a0980-48c8-11ea-8681-58f2681cfecd.png)

Does not work in current version:
![image](https://user-images.githubusercontent.com/3187668/73906414-d4425f00-48c8-11ea-9b38-b301e611a2a1.png)

The rancher instance is itself running on Hetzner with full internet access so I don't think it's a network issue.

**Comment by mxschmitt** [comment]
You have to add it as a Node Driver, not as a Cluster Driver.
