### ISSUE TITLE
how to upgrade the CSI driver

### ISSUE THREAD

**Issue by hadifarnoud** [mxschmitt/ui-driver-hetzner#81]
Hello,

How can I upgrade to latest Hetzner CSI driver?

**Comment by mxschmitt** [comment]
I think this is not directly related to that project. This repo just contains the graphical user interface for the Docker machine driver: https://github.com/JonasProgrammer/docker-machine-driver-hetzner

And also this one does not use the CSI driver by Hetzner Cloud. If you use this, you need to upgrade it manually, for that check the docs out here: https://github.com/hetznercloud/csi-driver
