### ISSUE TITLE
cannot provision a node

### ISSUE THREAD

**Issue by hadifarnoud** [mxschmitt/ui-driver-hetzner#82]
When I provision a node on Rancher, I get this error
```
Error setting machine configuration from flags provided: --hetzner-image and --hetzner-image-id are mutually exclusive; Timeout waiting for ssh key
```
What you think is wrong here?

I set Download URL as https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/2.0.1/docker-machine-driver-hetzner_2.0.1_linux_amd64.tar.gz and custom UI URL to https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js

**Comment by mxschmitt** [comment]
Could you provide me all the information which you are using for creating a Node Template?

I tested it with Ubuntu-18 and it works fine.

**Comment by hadifarnoud** [comment]
![screencapture-cluster3-kamva-org-n-node-templates-2020-03-21-03_02_35](https://user-images.githubusercontent.com/589808/77211138-9ae44c80-6b20-11ea-9843-d279a1f12596.png)

**Comment by hadifarnoud** [comment]
```
{
"annotations": {
"ownerBindingsCreated": "true"
},
"baseType": "nodeTemplate",
"cloudCredentialId": null,
"created": "2020-03-04T11:40:45Z",
"createdTS": 1583322045000,
"creatorId": "user-tkf9v",
"driver": "hetzner",
"engineInstallURL": "https://releases.rancher.com/install-docker/18.09.sh",
"engineRegistryMirror": null,
"hetznerConfig": {
"apiToken": "sxUKWWA8TfzfBxbjgON5NZZXtvtki6oScBaavErA90gTVYPO00H4EqJTMZUxaEHt",
"existingKeyId": "0",
"existingKeyPath": "",
"image": "ubuntu-16.04",
"imageId": "1",
"serverLocation": "fsn1",
"serverType": "cx21",
"userData": ""
},
"id": "cattle-global-nt:nt-user-tkf9v-nt-5qppr",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"nodePools": "…/v3/nodePools?nodeTemplateId=cattle-global-nt%3Ant-user-tkf9v-nt-5qppr",
"nodes": "…/v3/nodes?nodeTemplateId=cattle-global-nt%3Ant-user-tkf9v-nt-5qppr",
"self": "…/v3/nodeTemplates/cattle-global-nt:nt-user-tkf9v-nt-5qppr",
"update": "…/v3/nodeTemplates/cattle-global-nt:nt-user-tkf9v-nt-5qppr"
},
"name": "worker",
"principalId": "local://user-tkf9v",
"state": "active",
"transitioning": "no",
"transitioningMessage": "",
"type": "nodeTemplate",
"useInternalIpAddress": true,
"uuid": "0288a0c2-18f0-4a2f-9e68-d3d0f74e518c"
}
```

```
{
"annotations": {
"ownerBindingsCreated": "true"
},
"baseType": "nodeTemplate",
"cloudCredentialId": null,
"created": "2020-03-04T11:40:45Z",
"createdTS": 1583322045000,
"creatorId": "user-tkf9v",
"driver": "hetzner",
"engineEnv": { },
"engineInstallURL": "https://releases.rancher.com/install-docker/18.09.sh",
"engineLabel": { },
"engineOpt": { },
"engineRegistryMirror": null,
"hetznerConfig": {
"apiToken": "sxUKWWA8TfzfBxbjgON5NZZXtvtki6oScBaavErA90gTVYPO00H4EqJTMZUxaEHt",
"existingKeyId": "0",
"existingKeyPath": "",
"image": "ubuntu-16.04",
"imageId": "1",
"serverLocation": "fsn1",
"serverType": "cx31",
"userData": ""
},
"id": "cattle-global-nt:nt-user-tkf9v-nt-c26f7",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"nodePools": "…/v3/nodePools?nodeTemplateId=cattle-global-nt%3Ant-user-tkf9v-nt-c26f7",
"nodes": "…/v3/nodes?nodeTemplateId=cattle-global-nt%3Ant-user-tkf9v-nt-c26f7",
"self": "…/v3/nodeTemplates/cattle-global-nt:nt-user-tkf9v-nt-c26f7",
"update": "…/v3/nodeTemplates/cattle-global-nt:nt-user-tkf9v-nt-c26f7"
},
"name": "master1",
"principalId": "local://user-tkf9v",
"state": "active",
"transitioning": "no",
"transitioningMessage": "",
"type": "nodeTemplate",
"useInternalIpAddress": true,
"uuid": "3379f6aa-789b-4cb5-8949-ff9391f0c069"
}
```

**Comment by mxschmitt** [comment]
> ```
> {
> "annotations": {
> "ownerBindingsCreated": "true"
> },
> "baseType": "nodeTemplate",
> "cloudCredentialId": null,
> "created": "2020-03-04T11:40:45Z",
> "createdTS": 1583322045000,
> "creatorId": "user-tkf9v",
> "driver": "hetzner",
> "engineInstallURL": "https://releases.rancher.com/install-docker/18.09.sh",
> "engineRegistryMirror": null,
> "hetznerConfig": {
> "apiToken": "********",
> "existingKeyId": "0",
> "existingKeyPath": "",
> "image": "ubuntu-16.04",
> "imageId": "1",
> "serverLocation": "fsn1",
> "serverType": "cx21",
> "userData": ""
> },
> "id": "cattle-global-nt:nt-user-tkf9v-nt-5qppr",
> "labels": {
> "cattle.io/creator": "norman"
> },
> "links": {
> "nodePools": "…/v3/nodePools?nodeTemplateId=cattle-global-nt%3Ant-user-tkf9v-nt-5qppr",
> "nodes": "…/v3/nodes?nodeTemplateId=cattle-global-nt%3Ant-user-tkf9v-nt-5qppr",
> "self": "…/v3/nodeTemplates/cattle-global-nt:nt-user-tkf9v-nt-5qppr",
> "update": "…/v3/nodeTemplates/cattle-global-nt:nt-user-tkf9v-nt-5qppr"
> },
> "name": "worker",
> "principalId": "local://user-tkf9v",
> "state": "active",
> "transitioning": "no",
> "transitioningMessage": "",
> "type": "nodeTemplate",
> "useInternalIpAddress": true,
> "uuid": "0288a0c2-18f0-4a2f-9e68-d3d0f74e518c"
> }
> ```
> 
> ```
> {
> "annotations": {
> "ownerBindingsCreated": "true"
> },
> "baseType": "nodeTemplate",
> "cloudCredentialId": null,
> "created": "2020-03-04T11:40:45Z",
> "createdTS": 1583322045000,
> "creatorId": "user-tkf9v",
> "driver": "hetzner",
> "engineEnv": { },
> "engineInstallURL": "https://releases.rancher.com/install-docker/18.09.sh",
> "engineLabel": { },
> "engineOpt": { },
> "engineRegistryMirror": null,
> "hetznerConfig": {
> "apiToken": "************",
> "existingKeyId": "0",
> "existingKeyPath": "",
> "image": "ubuntu-16.04",
> "imageId": "1",
> "serverLocation": "fsn1",
> "serverType": "cx31",
> "userData": ""
> },
> "id": "cattle-global-nt:nt-user-tkf9v-nt-c26f7",
> "labels": {
> "cattle.io/creator": "norman"
> },
> "links": {
> "nodePools": "…/v3/nodePools?nodeTemplateId=cattle-global-nt%3Ant-user-tkf9v-nt-c26f7",
> "nodes": "…/v3/nodes?nodeTemplateId=cattle-global-nt%3Ant-user-tkf9v-nt-c26f7",
> "self": "…/v3/nodeTemplates/cattle-global-nt:nt-user-tkf9v-nt-c26f7",
> "update": "…/v3/nodeTemplates/cattle-global-nt:nt-user-tkf9v-nt-c26f7"
> },
> "name": "master1",
> "principalId": "local://user-tkf9v",
> "state": "active",
> "transitioning": "no",
> "transitioningMessage": "",
> "type": "nodeTemplate",
> "useInternalIpAddress": true,
> "uuid": "3379f6aa-789b-4cb5-8949-ff9391f0c069"
> }
> ```

which values have you changed on the frontend in the modal?

**Comment by hadifarnoud** [comment]
![screencapture-cluster3-kamva-org-n-node-templates-2020-03-21-03_02_35](https://user-images.githubusercontent.com/589808/77211510-d29fc400-6b21-11ea-9ed4-b6c4cec89b43.png)

Size, Region,

**Comment by mxschmitt** [comment]
could you try to select ubuntu-18?

**Comment by hadifarnoud** [comment]
would that be ok since other nodes are probably ubuntu 16?

**Comment by hadifarnoud** [comment]
I get the same error 
`Error setting machine configuration from flags provided: --hetzner-image and --hetzner-image-id are mutually exclusive; Timeout waiting for ssh key`

**Comment by mxschmitt** [comment]
Hm strange, I cant reproduce this :/

**Comment by hadifarnoud** [comment]
is there any logs we can take a look at?

**Comment by hadifarnoud** [comment]
interesting. I just created a new template and it worked just fine.

**Comment by hadifarnoud** [comment]
I just found something else. When I update the image to anything else, API still shows ubuntu 16

**Comment by hadifarnoud** [comment]
I've fixed it. I did go to API and changed the image name to 18.04

I also changed "network":null to "network":""
that allowed me to send the request. nodes created normally now

**Comment by mxschmitt** [comment]
> I've fixed it. I did go to API and changed the image name to 18.04
> 
> I also changed "network":null to "network":""
> that allowed me to send the request. nodes created normally now

awesome! do you think thats something we can fix here in the scope of this repository? So basically the fix was to change ubuntu16 by ubuntu 18?

**Comment by hadifarnoud** [comment]
I've no idea how this works but something went wrong that caused the image name and image Id not match (I think, not sure)

even if you make 18 default (which is a good idea anyway), it wouldn't help cases like me unless creating new node template
