### ISSUE TITLE
Stuck at Waiting for SSH to be available...	

### ISSUE THREAD

**Issue by boris-savic** [mxschmitt/ui-driver-hetzner#86]
Hi,

I'm trying to deploy new cluster by using pretty much standard config - only attaching private network and marked use private network for communication. If I understand those two features correctly, it means that nodes within that cluster will communicate via internal network provided by Hetzner. 

Config:
![defult-conf](https://user-images.githubusercontent.com/1744926/78120809-da594580-740a-11ea-9aff-1eb0c5d68d2d.PNG)

The above image shows all configs I've set - so nothing custom and even after an hour + the node is stuck at *Waiting for SSH to be available...*

I'm using Rancher 2.3.6 and UI Driver 2.1.0 (latest). 

Thanks for the help in advance!

**Comment by mxschmitt** [comment]
Hey, just as a first investigation, did you read already over that?
https://github.com/mxschmitt/ui-driver-hetzner#how-secure-is-the-private-network-feature

So the important one is Hetzner site-url needs to be the internal IP one and the Rancher host needs to be inside the Private Network of course.

**Comment by boris-savic** [comment]
Ugh, my bad. I somehow missed that Rancher host also needs to be in the same private network. 

So just to clarify - within the cluster host-2-host communication doesnt work via private network if I uncheck the *Use private network* flag?

**Comment by mxschmitt** [comment]
if you use this "use private network flag" that means, that the internal IP address of the private network will be used for host2host communication. So the k8 communicate e.g. or the communication between services if you have some communicating cross-host.

If you dont use this "use private network flag" that means, that the external IP address will be used for communication.

**Comment by boris-savic** [comment]
Understood. So basically if Rancher host is not on the same Private Network there is no way to enable host2host private network communication. 

Any plans on adding that feature?

**Comment by mxschmitt** [comment]
> Understood. So basically if Rancher host is not on the same Private Network there is no way to enable host2host private network communication.
> 
> Any plans on adding that feature?

This is something what Hetzner Cloud does not support. So it's not possible to add that.

**Comment by mxschmitt** [comment]
Closed since it's no issue with the driver itself.

**Comment by boris-savic** [comment]
What I wanted to achieve is: cluster nodes should communicate via internal network, so I dont have to open firewall on each one of them for every other node.

I managed to do this by:
Replacing in `cluster.yaml` (editing the Cluster YAML file inside rancher)
```yaml
network:
    plugin: "canal"
```

Replace with: 
```yaml
network:
    plugin: "canal"
    canal_network_provider:
        iface: "ens10"
```

So it uses the ens10 interface for the canal network.  It was my understanding that setting the use private IP to true would do that.
