### ISSUE TITLE
Missing SSH Key definition?

### ISSUE THREAD

**Issue by embcla** [mxschmitt/ui-driver-hetzner#90]
Hello

I am lost as to how to tell rancher 2.x which ssh key to use to access the nodes.
Presently I have mine setup in my account on Hetzner cloud, but there is nowhere to tell Rancher or your module to use one such key.

Moreover when I create a cluster, nodes stay in "waiting for ssh to be available" and when I check on my Hetzner account, I see there are new keys one for each node.

Can you explain what am I doing wrong?

**Comment by mxschmitt** [comment]
Rancher is generating alway a keypair for you. If you want to connect to the Hosts which Rancher has created, then you can do this by downloading the keys from the webinterface or using Rancher CLI (rancher ssh if I remember correctly. You could afaik also use Cloud Init for that to add your own public keys.

**Comment by embcla** [comment]
Hi and thanks for your replies

Ok I got it that rancher creates them, but my nodes in stay waiting for ssh forever
I downloaded the key and I can access the node

I'll investigate the cloud init, thank you!

**Comment by mxschmitt** [comment]
> Hi and thanks for your replies
> 
> Ok I got it that rancher creates them, but my nodes in stay waiting for ssh forever
> I downloaded the key and I can access the node
> 
> I'll investigate the cloud init, thank you!

Its important, that the Rancher base URL is accessible from the newly created hosts. Are you using the private networking feature?

**Comment by embcla** [comment]
my url is reachable yes (using a domain of mine) and I am asking for private network yes
should I not?

**Comment by mxschmitt** [comment]
> my url is reachable yes (using a domain of mine) and I am asking for private network yes
> should I not?
Using a private network has some pitfalls see here: https://github.com/mxschmitt/ui-driver-hetzner#requirements-for-private-network

So basically they must be in the same network as the Rancher host itself.

**Comment by embcla** [comment]
ok great thanks that solved the waiting forever!

the private network part then confuses me a bit here: shouldn't it do something like update the backend to use wireguard or something similar to hide the inter node comms?

**Comment by mxschmitt** [comment]
> ok great thanks that solved the waiting forever!
> 
> the private network part then confuses me a bit here: shouldn't it do something like update the backend to use wireguard or something similar to hide the inter node comms?

Yep exactly. You can use Weave or something like that. It's just a isolation on Hetzner Cloud side as documented in the readme.
