### ISSUE TITLE
doesn't work with Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by ceelian** [mxschmitt/ui-driver-hetzner#91]
Rancher Nodes reporting:

`Error creating machine: Error running provisioning: error installing docker:`

**Comment by mxschmitt** [comment]
I'll take a look later. Could you try to use a recent (if not) docker install script? Thats selectable in the bottom section of the Node configuration.

**Comment by mxschmitt** [comment]
Probably its related to that: https://github.com/docker/docker-install/issues/169

I tried both versions, 19.03 and latest (get.docker.com). Both will error and result in: `error installing docker`

**Comment by ceelian** [comment]
Thx for investigating. No, I hadn' time yet to test with docker install script. But feels like it is related to the bug you mentioned.

**Comment by nicktags** [comment]
apt install docker.io will work until the repo is fixed.

**Comment by StefanScherer** [comment]
Stay tuned, Docker 19.03.9 should be shipped this week.

**Comment by StefanScherer** [comment]
Docker 19.03.9 is released, with packages for Ubuntu Focal Fossa.
Thanks for you patience. Enjoy!

**Comment by mxschmitt** [comment]
I can confirm that it works with `https://get.docker.com` thanks!

For the official Rancher install scripts we have to wait until that the Rancher docker-install scripts are updated: https://github.com/rancher/rancher/issues/26783#issuecomment-630652891
