### ISSUE TITLE
AccessDenied

### ISSUE THREAD

**Issue by wirwolf** [mxschmitt/ui-driver-hetzner#94]
https://cluster.com/meta/proxy/https:/storage.googleapis.com/hcloud-rancher-v2-ui-driver/component-v20.css
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>
```

**Comment by mxschmitt** [comment]
Are you still using Rancher 2.0?

**Comment by mxschmitt** [comment]
This version is specific for Rancher 2.0. Your issue is btw. fixed, but I recommend to use the latest version.
