### ISSUE TITLE
Using private network and the kubeconfig

### ISSUE THREAD

**Issue by vitobotta** [mxschmitt/ui-driver-hetzner#97]
Hi,

I am testing again using a private network with the node driver since I am thinking of moving back to Hetzner Cloud.

I deployed Rancher and a cluster in the same project so they can share the same private network. The cluster was deployed but the kubeconfig generated by Rancher has the private IPs of the nodes, not the public ones, so I cannot connect to the cluster for example from my Mac.

I can only connect to the cluster using Rancher as a proxy, which isn't optimal. Is there a workaround?

Thanks!

**Comment by mxschmitt** [comment]
Hi @vitobotta,

I'm not using the driver anymore, so unfortunately not sure. I saw in the other GitHub issue, did you already found a workaround?

**Comment by vitobotta** [comment]
Hi @mxschmitt 

Yeah I found a workaround for that using an authorized endpoint with a load balancer and a fqdn. This way the kubeconfig was pointing to the load balancer instead of private IPs.

However I had to also find workarounds for other stuff.... so I changed mind quickly about going back to self managed after wasting almost one day with these issues.

I actually switched to DigitalOcean's managed services (Kubernetes and databases) one month ago and I was finally able to focus 100% on my project and forget about maintenance headaches. Because it's more expensive, I thought I'd try with Rancher and Hetzner Cloud again... but it looks like every time I find a solution to a problem, another two problems come up. I really didn't miss this at all.

I am a team of one so I got tired of spending too much time with that stuff. I will stick with DO managed services for now. It's just easier. 

May I ask, what are you using now?

Thanks

**Comment by mxschmitt** [comment]
Once I've created the driver (around 2017) I was using it for hosting Go based microservices for a startup. But this startup was running only around 2,5 years so I stopped with using it in the end.
For my main job we are also using Rancher, but with EC2 and docker machine (migrate to EKS in the future) on AWS.

**Comment by mxschmitt** [comment]
Closing since its more docker driver related. If i remember we had this topic a few months ago already coming up and the issue was that the upstream docker machine integration does not support it.
